### ISSUE TITLE
A plataforma está incrivelmente lenta e apresenta mensagens de erro

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#155]
Este lenta durante todo o dia. 

O erro foi ao logar clicando em edit. Deve ter demorado uns 30 segundos para entrar e depois surgiu a mensagem de logado com sucesso e uma mensagem de erro abaixo.

**Comment by gutosurrex** [comment]
Eu tentei aqui e hoje está boa...

Com você assim sempre lenta ou foi só um dia?

Você já está conseguindo logar de novo?

**Comment by gutosurrex** [comment]
Se o erro que você está recebendo é esse:

```
NameError("global name '_' is not defined",)


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_user/decorators.py", line 27, in decorated_view
    return func(*args, **kwargs)
  File "/var/www/BookCloud/application/views.py", line 1037, in edit
    build(project, branch)
  File "/var/www/BookCloud/application/views.py", line 321, in build
    process.run(timeout=timeout)
  File "/var/www/BookCloud/application/tools/__init__.py", line 57, in run
    flash(_('Process is taking too long and will be terminated!'), 'error')
NameError: global name '_' is not defined
```

Então pode ser alguma coisa que não está compilando no TeX, tipo uma linha sem `;` em uma figura tikz.

**Comment by simas0** [comment]
Não pode aparecer um erro assim quando a pessoa clica em editar... Parece um erro da plataforma. No mínimo devia ser indicado que o usuário clique em "refresh" no navegador para prosseguir.
